spring:
  application:
    name: schoolar
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}/
          jwk-set-uri: ${OAUTH_ISSUER_URI}/.well-known/jwks.json
