name: CI-CD Swarm
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build app (Maven)
        run: mvn -q -DskipTests package spring-boot:repackage

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image ref (lowercase)
        run: |
          OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}
          REPO_LC=${GITHUB_REPOSITORY#*/}
          REPO_LC=${REPO_LC,,}
          echo "OWNER_LC=$OWNER_LC" >> $GITHUB_ENV
          echo "REPO_LC=$REPO_LC"   >> $GITHUB_ENV
          echo "IMAGE=${REGISTRY}/${OWNER_LC}/${REPO_LC}:latest" >> $GITHUB_ENV

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env: 
      SSH_USER: azureuser
    steps:
      - uses: actions/checkout@v4

      - name: Copy deploy artifacts to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: azureuser
          key: ${{ secrets.SSH_KEY }}
          source: "deploy/*"
          target: "/home/azureuser/"

      - name: Deploy to Swarm via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: azureuser
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
            REPO_LC=$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')

            export GITHUB_OWNER="${OWNER_LC}"
            export REPO_NAME="${REPO_LC}"
            export DB_PASSWORD="${DB_PASSWORD}"

            docker login ghcr.io -u "${GITHUB_ACTOR}" -p "${GITHUB_TOKEN}"
            docker pull "ghcr.io/${OWNER_LC}/${REPO_LC}:latest" || true

            docker stack deploy -c "/home/${SSH_USER}/deploy/docker-stack.yml" swarmdemo

            docker service ls
            docker service ps swarmdemo_app
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
