name: Trigger auto deployment for scholar-service

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  AZURE_CONTAINER_REGISTRY: scholarservice
  CONTAINER_APP_NAME: hello
  RESOURCE_GROUP: Schoolar
  ENV_VAR: ${{ vars.ENV_CONTEXT_VAR }}
  OAUTH_ISSUER_URI: ${{ vars.OAUTH_ISSUER_URI }}

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    name: Welcome to the job
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    steps:
      - name: Print environment variables
        run: |
          echo "ISSUER_URI: ${{ env.OAUTH_ISSUER_URI }}"
          echo "AUDIENCE: ${{ vars.OAUTH_ISSUER_URI }}"
          echo "variable from shell environment : $ENV_VAR"

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          file: ./Dockerfile

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}



